name: Sync to Hugging Face Spaces

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Backend to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd backend
          rm -rf uploads/*
          mkdir -p uploads/mri_scans uploads/gradcam uploads/reports
          git config --global user.email "krishnamgupta123@gmail.com"
          git config --global user.name "krishnamgupta123"
          git init
          git checkout -b main
          git add .
          git commit -m "Deploy NeuroAssist Backend to Hugging Face"
          git push -f https://krishnamgupta123:${HF_TOKEN}@huggingface.co/spaces/krishnamgupta123/Neuro main
